### PR TITLE
fixed clion osx build

### PR DESCRIPTION
**Pull request by bagobor**
subj.

### CODE REVIEW

**Comment by bagobor** [comment]
I also updated dependencies so it works now :)

**Comment by bagobor** [comment]
but resource loading still should be fixed. may be I'll look for it tomorrow. 
thanks for nice Clion compatible code base example!

**Comment by mcleary** [comment]
Thanks for my ever pull request. I really appreciate it.

About your build fix. Since I'm using CMake I wasn't expecting any problems with cross plataform builds. This code was tested in Windows 10 with Visual Studio and macOS with XCode. 

The modifications you've made were due to issues building pbr in CLion?

**Comment by bagobor** [comment]
Hehe )) I'm glad to be helpful.

Yes, I'm using OSX + CLion.
 it actually 2 problems:
1. compile error due to GLFW include OpenGL foundation witch conflicts with glbingings. (so I added GLFW_INCLUDE_NONE define)
2. Bundle resources. By default no bundle is created and resources wasn't added/copied. Fixed by modifying Cmake file. (I used glfw cmake as reference) (see my 2nd pull request)

**Pull request merged**
